const path = require("path");
const { createFilePath } = require('gatsby-source-filesystem');

exports.onCreateNode = ({ node, getNode, actions }) => {
  const { createNodeField } = actions;

  if (node.internal.type === 'MarkdownRemark') {
    const slug = createFilePath({ node, getNode, basePath: 'content' });
    const { frontmatter } = node;

    // Assuming your 'frontmatter' has a 'path' and 'lang' field
    createNodeField({
      node,
      name: 'path',
      value: frontmatter.path || '/default-path',
    });

    createNodeField({
      node,
      name: 'lang',
      value: frontmatter.lang || 'en',
    });
  }
};

exports.onCreatePage = ({  graphql, page, actions }) => {
  const { createPage, deletePage } = actions;

  // Check if the page is created by the Gatsby i18n plugin
  if (page.path.includes('/home/home')) {
    delete page.context.path;
    // Get the original path generated by the plugin
    const originalPath = page.path;

    // Remove the duplicated "home" segment from the path
    const newPath = originalPath.replace(/\/home\/home/, '/home');

    // Delete the original page
    deletePage(page);

    // Create a new page with the modified path
    createPage({
      ...page,
      path: newPath,
    });
  }
};