import React from "react";

const SocialFollow = () => {
	return (
		<ecl-social-media-follow
		  variant="horizontal"
		  description="Follow the latest progress and get involved."
		>
		  <ecl-social-media-follow-item
		    icon="facebook-color"
		    share-path="http://facebook.com"
		  >
		    Facebook
		  </ecl-social-media-follow-item>
		  <ecl-social-media-follow-item
		    icon="twitter-color"
		    share-path="http://twitter.com"
		  >
		    Twitter
		  </ecl-social-media-follow-item>
		  <ecl-social-media-follow-item
		    icon="instagram-color"
		    share-path="http://instagram.com"
		  >
		    Instagram
		  </ecl-social-media-follow-item>
		  <ecl-social-media-follow-item
		    icon="linkedin-color"
		    share-path="http://linkedin.com"
		  >
		    Linkedin
		  </ecl-social-media-follow-item>
		  <ecl-social-media-follow-item
		    icon="telegram-color"
		    share-path="http://telegram.com"
		  >
		    Telegram
		  </ecl-social-media-follow-item>
		  <ecl-popover
		    ecl-script
		    toggle-label="Other social networks"
		    list
		    icon="share"
		    icon-size="s"
		    item-id="popover-example"
		  >
		    <ecl-popover-item
		      path="/example"
		      icon="pinterest-color"
		      icon-sprite="icons-social-media"
		      icon-size="s"
		    >
		      Pinterest
		    </ecl-popover-item>
		    <ecl-popover-item
		      path="/example"
		      icon="mastodon-color"
		      icon-sprite="icons-social-media"
		      icon-size="s"
		    >
		      Mastodon
		    </ecl-popover-item>
		    <ecl-popover-item
		      path="/example"
		      icon="reddit-color"
		      icon-sprite="icons-social-media"
		      icon-size="s"
		    >
		      Reddit
		    </ecl-popover-item>
		    <ecl-popover-item
		      path="/example"
		      icon="youtube-color"
		      icon-sprite="icons-social-media"
		      icon-size="s"
		    >
		      Youtube
		    </ecl-popover-item>
		    <ecl-popover-item
		      path="/example"
		      icon="flickr-color"
		      icon-sprite="icons-social-media"
		      icon-size="s"
		    >
		      Flickr
		    </ecl-popover-item>
		    <ecl-popover-item
		      path="/example"
		      icon="skype-color"
		      icon-sprite="icons-social-media"
		      icon-size="s"
		    >
		      Skype
		    </ecl-popover-item>
		  </ecl-popover>
		</ecl-social-media-follow>
	);
};

export default SocialFollow;
