backend:
  name: git-gateway
  repo: planctus/ecl-gatsby
  branch: master
  base_url: https://ecl-gatsby.netlify.app/
  extension: md
  squash_merges: true
  commit_messages:
    create: 'feat({{collection}}): create {{collection}} “{{slug}}”'
    update: 'feat({{collection}}): update {{collection}} “{{slug}}”'
    delete: 'feat({{collection}}): delete {{collection}} “{{slug}}”'
    uploadMedia: 'Upload “{{path}}”'
    deleteMedia: 'Delete “{{path}}”'

#local_backend: true
media_folder: src/images
publish_mode: editorial_workflow

collections:
  - label: 'Docs'
    name: 'docs'
    files:
      - label: 'Agenda for Europe'
        name: 'index'
        file: 'src/pages/agenda.md'
        fields:
          - { label: Body, name: body, widget: markdown }
